#!/usr/bin/env bash
#===========================================
#
#  @file log-tmux
#
#===========================================


DATE=`date "+%Y-%m-%d"`
TIME=`date "+%Hh%Mm%Ss"`
LOG_DIR=$HOME/logs/tmux/$DATE
LOG_FILE=$LOG_DIR/tmux-$DATE_$TIME-$1.log
mkdir -p $LOG_DIR
tmux display-message "Started logging to $LOG_FILE"

cat | perl -pse '$|=1; s/\n/\n${date}/g' -- -date="[$(date +%Y-%m-%d_%H:%M:%S:%N)]" >> $LOG_FILE

tmux display-message "end logging to $LOG_FILE"

#===========================================
#		   EOF
#===========================================

